version: '3'

services:
  web-server:
    build:
      context: ./web-server
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ./web-server:/app
      - /app/node_modules
      - uploads_data:/app/uploads
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-3000}
      - DB_HOST=${DB_HOST:-mysql}
      - DB_USER=${DB_USER:-touchgrass}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_NAME=${DB_NAME:-touchgrass_db}
    restart: unless-stopped
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpassword}
      - MYSQL_DATABASE=${DB_NAME:-touchgrass_db}
      - MYSQL_USER=${DB_USER:-touchgrass}
      - MYSQL_PASSWORD=${DB_PASSWORD:-password}
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

volumes:
  uploads_data:
  mysql_data: